name: 'Test env secrets'
on: [ push, workflow_dispatch ]

jobs:
  get_env_secrets:
    
    environment: dev
    
    runs-on: ubuntu-latest

    steps:
    
      - name: dump
    
        env: 
          super_secret: ${{secrets.ENV_SECRET}}
    
        run: |
          echo "This is the REPO SECRET $(echo ${{secrets.REPO_SECRET}} | sed 's/./& /g')"
          echo "This is the ENV SECRET $(echo ${{secrets.ENV_SECRET}}  | sed 's/./& /g')"
          echo "This is the env SECRET $(echo $super_secret | sed 's/./& /g')"

      - name: 'Dump Env and Secrets'
        uses: allenarceneaux/dump-vars@main
        with:
          the_secrets: ${{ toJson(secrets) }} 
