name: 'Test env secrets'
on: [ push, workflow_dispatch ]

jobs:
  get_env_secrets:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: dump
        env: 
          super_secret: ${{secrets.ENV_SECRET}}
        run: |
          echo "This is the REPO SECRET ${{secrets.REPOL_SECRET}} environment variable"
          echo "This is the ENV SECRET ${{secrets.ENV_SECRET}} environment variable"
          echo "This is the env SECRET $super_secret environment variable"

      - name: 'Dump Env and Secrets'
        uses: allenarceneaux/dump-vars@main
        with:
          the_secrets: ${{ toJson(secrets) }} 
